# Generated by Django 5.0 on 2023-12-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
